import type { ProductionStage } from "@prisma/client";

/**
 * Tahapan produksi dipetakan ke fase kerjanya agar warna bermakna,
 * mengikuti kosakata warna semantik yang sama dengan Pipeline CRM:
 * - Fase desain dan persetujuan sampel -> highlight
 * - Fase eksekusi produksi -> primary
 * - QC -> warning
 * - Packing dan pengiriman -> info
 * - Selesai -> success
 */
const PHASE_SURFACE_CLASS = {
  DESIGN: "border-highlight/20 bg-highlight/5",
  EXECUTION: "border-primary/20 bg-primary/5",
  CHECK: "border-warning/20 bg-warning/5",
  OUTBOUND: "border-info/20 bg-info/5",
  DONE: "border-success/20 bg-success/5",
} as const;

const PHASE_TEXT_CLASS = {
  DESIGN: "text-highlight",
  EXECUTION: "text-primary",
  CHECK: "text-warning",
  OUTBOUND: "text-info",
  DONE: "text-success",
} as const;

const PHASE_SUMMARY_CLASS = {
  DESIGN: "bg-highlight/5",
  EXECUTION: "bg-primary/5",
  CHECK: "bg-warning/5",
  OUTBOUND: "bg-info/5",
  DONE: "bg-success/5",
} as const;

const PHASE_BADGE_VARIANT = {
  DESIGN: "highlight",
  EXECUTION: "default",
  CHECK: "warning",
  OUTBOUND: "info",
  DONE: "success",
} as const;

export const STAGE_SURFACE_CLASS: Record<ProductionStage, string> = {
  TEST_PRINT: PHASE_SURFACE_CLASS.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_SURFACE_CLASS.DESIGN,
  LAYOUT_PRODUKSI: PHASE_SURFACE_CLASS.DESIGN,
  POTONG: PHASE_SURFACE_CLASS.EXECUTION,
  BORDIR: PHASE_SURFACE_CLASS.EXECUTION,
  SABLON: PHASE_SURFACE_CLASS.EXECUTION,
  PRINTING: PHASE_SURFACE_CLASS.EXECUTION,
  PRINT: PHASE_SURFACE_CLASS.EXECUTION,
  CUTTING: PHASE_SURFACE_CLASS.EXECUTION,
  JAHIT: PHASE_SURFACE_CLASS.EXECUTION,
  QC: PHASE_SURFACE_CLASS.CHECK,
  PACKING: PHASE_SURFACE_CLASS.OUTBOUND,
  PENGIRIMAN: PHASE_SURFACE_CLASS.OUTBOUND,
  SELESAI: PHASE_SURFACE_CLASS.DONE,
};

export const STAGE_TEXT_CLASS: Record<ProductionStage, string> = {
  TEST_PRINT: PHASE_TEXT_CLASS.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_TEXT_CLASS.DESIGN,
  LAYOUT_PRODUKSI: PHASE_TEXT_CLASS.DESIGN,
  POTONG: PHASE_TEXT_CLASS.EXECUTION,
  BORDIR: PHASE_TEXT_CLASS.EXECUTION,
  SABLON: PHASE_TEXT_CLASS.EXECUTION,
  PRINTING: PHASE_TEXT_CLASS.EXECUTION,
  PRINT: PHASE_TEXT_CLASS.EXECUTION,
  CUTTING: PHASE_TEXT_CLASS.EXECUTION,
  JAHIT: PHASE_TEXT_CLASS.EXECUTION,
  QC: PHASE_TEXT_CLASS.CHECK,
  PACKING: PHASE_TEXT_CLASS.OUTBOUND,
  PENGIRIMAN: PHASE_TEXT_CLASS.OUTBOUND,
  SELESAI: PHASE_TEXT_CLASS.DONE,
};

export const STAGE_SUMMARY_CLASS: Record<ProductionStage, string> = {
  TEST_PRINT: PHASE_SUMMARY_CLASS.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_SUMMARY_CLASS.DESIGN,
  LAYOUT_PRODUKSI: PHASE_SUMMARY_CLASS.DESIGN,
  POTONG: PHASE_SUMMARY_CLASS.EXECUTION,
  BORDIR: PHASE_SUMMARY_CLASS.EXECUTION,
  SABLON: PHASE_SUMMARY_CLASS.EXECUTION,
  PRINTING: PHASE_SUMMARY_CLASS.EXECUTION,
  PRINT: PHASE_SUMMARY_CLASS.EXECUTION,
  CUTTING: PHASE_SUMMARY_CLASS.EXECUTION,
  JAHIT: PHASE_SUMMARY_CLASS.EXECUTION,
  QC: PHASE_SUMMARY_CLASS.CHECK,
  PACKING: PHASE_SUMMARY_CLASS.OUTBOUND,
  PENGIRIMAN: PHASE_SUMMARY_CLASS.OUTBOUND,
  SELESAI: PHASE_SUMMARY_CLASS.DONE,
};

export const STAGE_BADGE_VARIANT: Record<ProductionStage, "highlight" | "default" | "warning" | "info" | "success"> = {
  TEST_PRINT: PHASE_BADGE_VARIANT.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_BADGE_VARIANT.DESIGN,
  LAYOUT_PRODUKSI: PHASE_BADGE_VARIANT.DESIGN,
  POTONG: PHASE_BADGE_VARIANT.EXECUTION,
  BORDIR: PHASE_BADGE_VARIANT.EXECUTION,
  SABLON: PHASE_BADGE_VARIANT.EXECUTION,
  PRINTING: PHASE_BADGE_VARIANT.EXECUTION,
  PRINT: PHASE_BADGE_VARIANT.EXECUTION,
  CUTTING: PHASE_BADGE_VARIANT.EXECUTION,
  JAHIT: PHASE_BADGE_VARIANT.EXECUTION,
  QC: PHASE_BADGE_VARIANT.CHECK,
  PACKING: PHASE_BADGE_VARIANT.OUTBOUND,
  PENGIRIMAN: PHASE_BADGE_VARIANT.OUTBOUND,
  SELESAI: PHASE_BADGE_VARIANT.DONE,
};
