import type { ProductionStage } from "@prisma/client";

/**
 * Kolom tetap netral agar board mudah dipindai. Warna hanya menandai
 * label fase: pekerjaan aktif, pemeriksaan, pengiriman, dan selesai.
 */
const PHASE_SURFACE_CLASS = {
  DESIGN: "border-border bg-muted/30",
  EXECUTION: "border-border bg-muted/30",
  CHECK: "border-border bg-muted/30",
  OUTBOUND: "border-border bg-muted/30",
  DONE: "border-border bg-muted/30",
} as const;

const PHASE_TEXT_CLASS = {
  DESIGN: "text-foreground",
  EXECUTION: "text-primary",
  CHECK: "text-warning",
  OUTBOUND: "text-info",
  DONE: "text-success",
} as const;

const PHASE_SUMMARY_CLASS = {
  DESIGN: "bg-card",
  EXECUTION: "bg-card",
  CHECK: "bg-card",
  OUTBOUND: "bg-card",
  DONE: "bg-card",
} as const;

const PHASE_BADGE_VARIANT = {
  DESIGN: "outline",
  EXECUTION: "default",
  CHECK: "warning",
  OUTBOUND: "info",
  DONE: "success",
} as const;

export const STAGE_SURFACE_CLASS: Record<ProductionStage, string> = {
  TEST_PRINT: PHASE_SURFACE_CLASS.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_SURFACE_CLASS.DESIGN,
  LAYOUT_PRODUKSI: PHASE_SURFACE_CLASS.DESIGN,
  POTONG: PHASE_SURFACE_CLASS.EXECUTION,
  BORDIR: PHASE_SURFACE_CLASS.EXECUTION,
  SABLON: PHASE_SURFACE_CLASS.EXECUTION,
  PRINTING: PHASE_SURFACE_CLASS.EXECUTION,
  PRINT: PHASE_SURFACE_CLASS.EXECUTION,
  CUTTING: PHASE_SURFACE_CLASS.EXECUTION,
  JAHIT: PHASE_SURFACE_CLASS.EXECUTION,
  QC: PHASE_SURFACE_CLASS.CHECK,
  PACKING: PHASE_SURFACE_CLASS.OUTBOUND,
  PENGIRIMAN: PHASE_SURFACE_CLASS.OUTBOUND,
  SELESAI: PHASE_SURFACE_CLASS.DONE,
};

export const STAGE_TEXT_CLASS: Record<ProductionStage, string> = {
  TEST_PRINT: PHASE_TEXT_CLASS.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_TEXT_CLASS.DESIGN,
  LAYOUT_PRODUKSI: PHASE_TEXT_CLASS.DESIGN,
  POTONG: PHASE_TEXT_CLASS.EXECUTION,
  BORDIR: PHASE_TEXT_CLASS.EXECUTION,
  SABLON: PHASE_TEXT_CLASS.EXECUTION,
  PRINTING: PHASE_TEXT_CLASS.EXECUTION,
  PRINT: PHASE_TEXT_CLASS.EXECUTION,
  CUTTING: PHASE_TEXT_CLASS.EXECUTION,
  JAHIT: PHASE_TEXT_CLASS.EXECUTION,
  QC: PHASE_TEXT_CLASS.CHECK,
  PACKING: PHASE_TEXT_CLASS.OUTBOUND,
  PENGIRIMAN: PHASE_TEXT_CLASS.OUTBOUND,
  SELESAI: PHASE_TEXT_CLASS.DONE,
};

export const STAGE_SUMMARY_CLASS: Record<ProductionStage, string> = {
  TEST_PRINT: PHASE_SUMMARY_CLASS.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_SUMMARY_CLASS.DESIGN,
  LAYOUT_PRODUKSI: PHASE_SUMMARY_CLASS.DESIGN,
  POTONG: PHASE_SUMMARY_CLASS.EXECUTION,
  BORDIR: PHASE_SUMMARY_CLASS.EXECUTION,
  SABLON: PHASE_SUMMARY_CLASS.EXECUTION,
  PRINTING: PHASE_SUMMARY_CLASS.EXECUTION,
  PRINT: PHASE_SUMMARY_CLASS.EXECUTION,
  CUTTING: PHASE_SUMMARY_CLASS.EXECUTION,
  JAHIT: PHASE_SUMMARY_CLASS.EXECUTION,
  QC: PHASE_SUMMARY_CLASS.CHECK,
  PACKING: PHASE_SUMMARY_CLASS.OUTBOUND,
  PENGIRIMAN: PHASE_SUMMARY_CLASS.OUTBOUND,
  SELESAI: PHASE_SUMMARY_CLASS.DONE,
};

export const STAGE_BADGE_VARIANT: Record<ProductionStage, "outline" | "default" | "warning" | "info" | "success"> = {
  TEST_PRINT: PHASE_BADGE_VARIANT.DESIGN,
  PERSETUJUAN_SAMPEL: PHASE_BADGE_VARIANT.DESIGN,
  LAYOUT_PRODUKSI: PHASE_BADGE_VARIANT.DESIGN,
  POTONG: PHASE_BADGE_VARIANT.EXECUTION,
  BORDIR: PHASE_BADGE_VARIANT.EXECUTION,
  SABLON: PHASE_BADGE_VARIANT.EXECUTION,
  PRINTING: PHASE_BADGE_VARIANT.EXECUTION,
  PRINT: PHASE_BADGE_VARIANT.EXECUTION,
  CUTTING: PHASE_BADGE_VARIANT.EXECUTION,
  JAHIT: PHASE_BADGE_VARIANT.EXECUTION,
  QC: PHASE_BADGE_VARIANT.CHECK,
  PACKING: PHASE_BADGE_VARIANT.OUTBOUND,
  PENGIRIMAN: PHASE_BADGE_VARIANT.OUTBOUND,
  SELESAI: PHASE_BADGE_VARIANT.DONE,
};
